### ISSUE TITLE
A quick question about the terminology "Album" in paper

### ISSUE THREAD

**Issue by linzhiqiu** [IntelLabs/continuallearning#1]
Hey I have a question related to the paper and I guess I will just post it here. The paper mention that the online accuracy will only be measured for the first album of the 256 images per iterations. Could you please clarify what this means with maybe a concrete example? Thanks!

**Comment by ZhipengCai** [comment]
Hi, the definition of the 'album' is: the first set of images in the 256 images that are uploaded by the same user. E.g., in the next 256 images, the first 2 images are uploaded by the user 'Peter', and the rest are uploaded not by Peter, then the first album contains the first 2 images.

Hope this clarifies the concept. And thanks for being interested in our work.
